import type { Room } from "./room.model";

export interface DB {
  rooms: Room[];
}

export const db: DB = {
  rooms: [{
    _id: "65097600a74000a4a4a22686",
    listing_url: "https://www.airbnb.com/rooms/10006546",
    name: "Ribeira Charming Duplex",
    summary:
      "Fantastic duplex apartment with three bedrooms in historic center.",
    space: "Privileged views of the Douro River and Ribeira square.",
    description:
      "Fantastic duplex apartment with three bedrooms, located in the historic center of Porto.",
    neighborhood_overview: "Close to river, restaurants, and shops.",
    notes: "Narrow streets and staircases nearby.",
    transit: "Metro station 5min walk, bus stop 2min walk.",
    access: "Full apartment access for guests.",
    interaction: "Hosts are available 24/7 via phone.",
    house_rules: "No smoking, no pets, quiet hours after 10pm.",
    property_type: "House",
    room_type: "Entire home/apt",
    bed_type: "Real Bed",
    minimum_nights: "2",
    maximum_nights: "30",
    cancellation_policy: "moderate",
    last_scraped: "2019-02-16T05:00:00.000Z",
    calendar_last_scraped: "2019-02-16T05:00:00.000Z",
    first_review: "2016-01-03T05:00:00.000Z",
    last_review: "2019-01-20T05:00:00.000Z",
    accommodates: 8,
    bedrooms: 3,
    beds: 5,
    number_of_reviews: 51,
    bathrooms: 1,
    amenities: [
      "WiFi",
      "Heating",
      "Kitchen",
      "Washer",
      "Dryer",
      "TV",
      "Smoke alarm",
    ],
    price: 80,
    security_deposit: 200,
    cleaning_fee: 35,
    extra_people: 15,
    guests_included: 6,
    images: {
      thumbnail_url: "https://example.com/thumb1.jpg",
      medium_url: "https://example.com/medium1.jpg",
      picture_url: "https://example.com/pic1.jpg",
      xl_picture_url: "https://example.com/xlpic1.jpg",
    },
    host: {
      host_id: "12345",
      host_url: "https://www.airbnb.com/users/show/12345",
      host_name: "Alice",
      host_location: "Porto",
      host_about: "Experienced host, love meeting new people.",
      host_response_time: "within an hour",
      host_thumbnail_url: "https://example.com/hostthumb1.jpg",
      host_picture_url: "https://example.com/hostpic1.jpg",
      host_neighbourhood: "Downtown Porto",
      host_is_superhost: true,
      host_has_profile_pic: true,
      host_identity_verified: true,
      host_listings_count: 3,
    },
    address: {
      street: "Rua da Ribeira 10",
      suburb: "Ribeira",
      government_area: "Porto",
      market: "Porto Center",
      country: "Portugal",
      country_code: "PT",
      location: {
        type: "Point",
        coordinates: [-8.611, 41.14],
        is_location_exact: true,
      },
    },
    availability: {
      availability_30: 20,
      availability_60: 45,
      availability_90: 70,
      availability_365: 300,
    },
    review_scores: {
      review_scores_accuracy: 9,
      review_scores_cleanliness: 10,
      review_scores_checkin: 9,
      review_scores_communication: 10,
      review_scores_location: 10,
      review_scores_value: 8,
      review_scores_rating: 9,
    },
    reviews: [
      {
        _id: "r1",
        date: "2019-01-10",
        reviewer_id: "u100",
        reviewer_name: "John Doe",
        comments: "Great stay, highly recommend!",
      },
      {
        _id: "r2",
        date: "2019-01-15",
        reviewer_id: "u101",
        reviewer_name: "Jane Smith",
        comments: "Lovely place and very clean.",
      },
    ],
  },
  {
    _id: "65097600a74000a4a4a22687",
    listing_url: "https://www.airbnb.com/rooms/10006547",
    name: "Cozy Studio Downtown",
    summary: "Perfect for couples, near city attractions.",
    space: "Compact studio with modern amenities.",
    description: "Cozy studio apartment ideal for short stays in downtown.",
    neighborhood_overview: "Close to museums and restaurants.",
    notes: "Quiet neighborhood.",
    transit: "Close to subway station.",
    access: "Self check-in via lockbox.",
    interaction: "Available by message.",
    house_rules: "No pets, no parties.",
    property_type: "Apartment",
    room_type: "Entire home/apt",
    bed_type: "Real Bed",
    minimum_nights: "1",
    maximum_nights: "15",
    cancellation_policy: "flexible",
    last_scraped: "2019-03-10T05:00:00.000Z",
    calendar_last_scraped: "2019-03-10T05:00:00.000Z",
    first_review: "2017-05-01T05:00:00.000Z",
    last_review: "2019-02-20T05:00:00.000Z",
    accommodates: 2,
    bedrooms: 0,
    beds: 1,
    number_of_reviews: 34,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Kitchen", "TV"],
    price: 50,
    security_deposit: 100,
    cleaning_fee: 20,
    extra_people: 10,
    guests_included: 1,
    images: {
      thumbnail_url: "https://example.com/thumb2.jpg",
      medium_url: "https://example.com/medium2.jpg",
      picture_url: "https://example.com/pic2.jpg",
      xl_picture_url: "https://example.com/xlpic2.jpg",
    },
    host: {
      host_id: "12346",
      host_url: "https://www.airbnb.com/users/show/12346",
      host_name: "Bob",
      host_location: "Lisbon",
      host_about: "Love hosting travelers.",
      host_response_time: "within a few hours",
      host_thumbnail_url: "https://example.com/hostthumb2.jpg",
      host_picture_url: "https://example.com/hostpic2.jpg",
      host_neighbourhood: "City Center",
      host_is_superhost: false,
      host_has_profile_pic: true,
      host_identity_verified: true,
      host_listings_count: 1,
    },
    address: {
      street: "Rua das Flores 5",
      suburb: "Centro",
      government_area: "Lisbon",
      market: "Lisbon Center",
      country: "Portugal",
      country_code: "PT",
      location: {
        type: "Point",
        coordinates: [-9.142, 38.722],
        is_location_exact: true,
      },
    },
    availability: {
      availability_30: 10,
      availability_60: 20,
      availability_90: 50,
      availability_365: 200,
    },
    review_scores: {
      review_scores_accuracy: 8,
      review_scores_cleanliness: 9,
      review_scores_checkin: 8,
      review_scores_communication: 9,
      review_scores_location: 9,
      review_scores_value: 8,
      review_scores_rating: 8,
    },
    reviews: [
      {
        _id: "r3",
        date: "2019-02-10",
        reviewer_id: "u102",
        reviewer_name: "Alice Johnson",
        comments: "Very cozy and well located.",
      },
    ],
  },
  {
    _id: "65097600a74000a4a4a22688",
    listing_url: "https://www.airbnb.com/rooms/10006548",
    name: "Modern Loft with Views",
    summary: "Spacious loft with river views.",
    space: "Open space loft with large windows.",
    description: "Modern loft located near the river with stunning views.",
    neighborhood_overview: "Trendy area with cafes and galleries.",
    notes: "Parking available nearby.",
    transit: "Bus stop 3 minutes away.",
    access: "Keypad entry system.",
    interaction: "Hosts live nearby.",
    house_rules: "No smoking, no pets.",
    property_type: "Loft",
    room_type: "Entire home/apt",
    bed_type: "Real Bed",
    minimum_nights: "3",
    maximum_nights: "30",
    cancellation_policy: "strict",
    last_scraped: "2019-01-20T05:00:00.000Z",
    calendar_last_scraped: "2019-01-20T05:00:00.000Z",
    first_review: "2017-07-15T05:00:00.000Z",
    last_review: "2019-01-10T05:00:00.000Z",
    accommodates: 4,
    bedrooms: 1,
    beds: 2,
    number_of_reviews: 20,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Kitchen", "TV", "Air conditioning"],
    price: 120,
    security_deposit: 300,
    cleaning_fee: 40,
    extra_people: 20,
    guests_included: 2,
    images: {
      thumbnail_url: "https://example.com/thumb3.jpg",
      medium_url: "https://example.com/medium3.jpg",
      picture_url: "https://example.com/pic3.jpg",
      xl_picture_url: "https://example.com/xlpic3.jpg",
    },
    host: {
      host_id: "12347",
      host_url: "https://www.airbnb.com/users/show/12347",
      host_name: "Charlie",
      host_location: "Porto",
      host_about: "Passionate about hosting.",
      host_response_time: "within a day",
      host_thumbnail_url: "https://example.com/hostthumb3.jpg",
      host_picture_url: "https://example.com/hostpic3.jpg",
      host_neighbourhood: "Ribeira",
      host_is_superhost: true,
      host_has_profile_pic: true,
      host_identity_verified: true,
      host_listings_count: 2,
    },
    address: {
      street: "Rua Nova 15",
      suburb: "Ribeira",
      government_area: "Porto",
      market: "Porto Center",
      country: "Portugal",
      country_code: "PT",
      location: {
        type: "Point",
        coordinates: [-8.61, 41.141],
        is_location_exact: true,
      },
    },
    availability: {
      availability_30: 25,
      availability_60: 50,
      availability_90: 75,
      availability_365: 320,
    },
    review_scores: {
      review_scores_accuracy: 10,
      review_scores_cleanliness: 10,
      review_scores_checkin: 9,
      review_scores_communication: 10,
      review_scores_location: 10,
      review_scores_value: 9,
      review_scores_rating: 10,
    },
    reviews: [
      {
        _id: "r4",
        date: "2019-01-05",
        reviewer_id: "u103",
        reviewer_name: "Eve Martin",
        comments: "Wonderful loft with great views.",
      },
    ],
  },
  {
    _id: "65097600a74000a4a4a22689",
    listing_url: "https://www.airbnb.com/rooms/10006549",
    name: "Seaside Cottage",
    summary: "Cozy cottage by the sea.",
    space: "Cottage with garden and terrace.",
    description: "Beautiful seaside cottage perfect for summer holidays.",
    neighborhood_overview: "Quiet village close to the beach.",
    notes: "Ideal for families.",
    transit: "Limited public transport.",
    access: "Private parking included.",
    interaction: "Hosts check in person.",
    house_rules: "No loud music after 9pm.",
    property_type: "Cottage",
    room_type: "Entire home/apt",
    bed_type: "Real Bed",
    minimum_nights: "4",
    maximum_nights: "28",
    cancellation_policy: "moderate",
    last_scraped: "2019-04-01T05:00:00.000Z",
    calendar_last_scraped: "2019-04-01T05:00:00.000Z",
    first_review: "2016-06-01T05:00:00.000Z",
    last_review: "2019-03-20T05:00:00.000Z",
    accommodates: 6,
    bedrooms: 2,
    beds: 3,
    number_of_reviews: 40,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Heating", "Fireplace"],
    price: 95,
    security_deposit: 250,
    cleaning_fee: 30,
    extra_people: 10,
    guests_included: 4,
    images: {
      thumbnail_url: "https://example.com/thumb4.jpg",
      medium_url: "https://example.com/medium4.jpg",
      picture_url: "https://example.com/pic4.jpg",
      xl_picture_url: "https://example.com/xlpic4.jpg",
    },
    host: {
      host_id: "12348",
      host_url: "https://www.airbnb.com/users/show/12348",
      host_name: "Diana",
      host_location: "Algarve",
      host_about: "Friendly host, love nature.",
      host_response_time: "within a few hours",
      host_thumbnail_url: "https://example.com/hostthumb4.jpg",
      host_picture_url: "https://example.com/hostpic4.jpg",
      host_neighbourhood: "Beachside",
      host_is_superhost: false,
      host_has_profile_pic: true,
      host_identity_verified: true,
      host_listings_count: 4,
    },
    address: {
      street: "Rua da Praia 20",
      suburb: "Praia",
      government_area: "Algarve",
      market: "Algarve Region",
      country: "Portugal",
      country_code: "PT",
      location: {
        type: "Point",
        coordinates: [-8.25, 37.02],
        is_location_exact: true,
      },
    },
    availability: {
      availability_30: 15,
      availability_60: 35,
      availability_90: 60,
      availability_365: 250,
    },
    review_scores: {
      review_scores_accuracy: 9,
      review_scores_cleanliness: 9,
      review_scores_checkin: 9,
      review_scores_communication: 10,
      review_scores_location: 9,
      review_scores_value: 8,
      review_scores_rating: 9,
    },
    reviews: [
      {
        _id: "r5",
        date: "2019-03-15",
        reviewer_id: "u104",
        reviewer_name: "Frank Lee",
        comments: "Perfect place for a relaxing vacation.",
      },
    ],
  },
  {
    _id: "65097600a74000a4a4a22690",
    listing_url: "https://www.airbnb.com/rooms/10006550",
    name: "Mountain Cabin Retreat",
    summary: "Rustic cabin with mountain views.",
    space: "Cabin surrounded by nature.",
    description: "Cozy mountain cabin perfect for hiking lovers.",
    neighborhood_overview: "Secluded area with trails.",
    notes: "Limited cell coverage.",
    transit: "No public transport nearby.",
    access: "Guests have full access.",
    interaction: "Hosts live nearby and available by phone.",
    house_rules: "No smoking, no loud parties.",
    property_type: "Cabin",
    room_type: "Entire home/apt",
    bed_type: "Real Bed",
    minimum_nights: "3",
    maximum_nights: "21",
    cancellation_policy: "strict",
    last_scraped: "2019-01-01T05:00:00.000Z",
    calendar_last_scraped: "2019-01-01T05:00:00.000Z",
    first_review: "2017-01-15T05:00:00.000Z",
    last_review: "2018-12-20T05:00:00.000Z",
    accommodates: 5,
    bedrooms: 2,
    beds: 3,
    number_of_reviews: 15,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Fireplace", "Kitchen"],
    price: 75,
    security_deposit: 150,
    cleaning_fee: 25,
    extra_people: 10,
    guests_included: 3,
    images: {
      thumbnail_url: "https://example.com/thumb5.jpg",
      medium_url: "https://example.com/medium5.jpg",
      picture_url: "https://example.com/pic5.jpg",
      xl_picture_url: "https://example.com/xlpic5.jpg",
    },
    host: {
      host_id: "12349",
      host_url: "https://www.airbnb.com/users/show/12349",
      host_name: "Ethan",
      host_location: "Sierra Nevada",
      host_about: "Nature lover and experienced host.",
      host_response_time: "within a day",
      host_thumbnail_url: "https://example.com/hostthumb5.jpg",
      host_picture_url: "https://example.com/hostpic5.jpg",
      host_neighbourhood: "Mountain area",
      host_is_superhost: false,
      host_has_profile_pic: true,
      host_identity_verified: false,
      host_listings_count: 1,
    },
    address: {
      street: "Calle Montaña 1",
      suburb: "Highlands",
      government_area: "Sierra Nevada",
      market: "Mountain Region",
      country: "Spain",
      country_code: "ES",
      location: {
        type: "Point",
        coordinates: [-3.4, 37.0],
        is_location_exact: true,
      },
    },
    availability: {
      availability_30: 5,
      availability_60: 15,
      availability_90: 30,
      availability_365: 100,
    },
    review_scores: {
      review_scores_accuracy: 8,
      review_scores_cleanliness: 9,
      review_scores_checkin: 8,
      review_scores_communication: 9,
      review_scores_location: 7,
      review_scores_value: 8,
      review_scores_rating: 8,
    },
    reviews: [
      {
        _id: "r6",
        date: "2018-12-15",
        reviewer_id: "u105",
        reviewer_name: "Grace Hopper",
        comments: "Peaceful retreat with beautiful nature.",
      },
    ],
  },
],
}
  